import turtle
def draw_steve(hair_color:str, skin_color:str, eye_pupil_color:str, eye_color:str, shirt_color:str, pants_color:str, boots_color:str):
    t = turtle.Pen()
    t.speed(0)
    # Head
    t.penup()
    t.setpos(x=0, y=50)
    t.pencolor(skin_color)
    t.fillcolor(skin_color)
    t.pendown()
    t.begin_fill()
    t.forward(30)
    for x in range(3):
        t.left(90)
        t.forward(60)
    t.left(90)
    t.forward(30)
    t.end_fill()
    # Hair
    t.penup()
    t.setpos(x=-30, y=90)
    t.pencolor(hair_color)
    t.fillcolor(hair_color)
    t.pendown()
    t.begin_fill()
    t.forward(10)
    t.left(90)
    t.forward(10)
    t.right(90)
    t.forward(40)
    t.right(90)
    t.forward(10)
    t.left(90)
    t.forward(10)
    t.left(90)
    t.forward(20)
    t.left(90)
    t.forward(60)
    t.left(90)
    t.forward(20)
    t.end_fill()
    # Eyes
    t.penup()
    t.setpos(x=-25, y=90)
    t.pencolor(eye_color)
    t.fillcolor(eye_color)
    t.pendown()
    t.begin_fill()
    for n in range(4):
        t.forward(10)
        t.left(90)
    t.end_fill()
    t.penup()
    t.setpos(x=15, y=90)
    t.pendown()
    t.begin_fill()
    for y in range(4):
        t.forward(10)
        t.left(90)
    t.end_fill()
    # Eye Pupils
    t.penup()
    t.setpos(x=-15, y=90)
    t.pencolor(eye_pupil_color)
    t.fillcolor(eye_pupil_color)
    t.pendown()
    t.begin_fill()
    for o in range(4):
        t.forward(10)
        t.left(90)
    t.end_fill()
    t.penup()
    t.setpos(x=5, y=90)
    t.pendown()
    t.begin_fill()
    for p in range(4):
        t.forward(10)
        t.left(90)
    t.end_fill()
    # Beard
    t.penup()
    t.setpos(x=-20, y=70)
    t.pencolor(hair_color)
    t.fillcolor(hair_color)
    t.pendown()
    t.begin_fill()
    t.left(90)
    for c in range(4):
        t.forward(10)
        t.right(90)
    t.end_fill()
    t.penup()
    t.setpos(x=10, y=70)
    t.pencolor(hair_color)
    t.fillcolor(hair_color)
    t.pendown()
    t.begin_fill()
    for m in range(4):
        t.forward(10)
        t.right(90)
    t.end_fill()
    t.penup()
    t.setpos(x=-20, y=60)
    t.pendown()
    t.begin_fill()
    for b in range(2):
        t.forward(40)
        t.right(90)
        t.forward(10)
        t.right(90)
    t.end_fill()
    # Shirt
    t.penup()
    t.setpos(x=-30, y=50)
    t.pencolor(shirt_color)
    t.fillcolor(shirt_color)
    t.pendown()
    t.right(90)
    t.begin_fill()
    for z in range(2):
        t.forward(80)
        t.left(90)
        t.forward(60)
        t.left(90)
    t.end_fill()
    # Pants
    t.penup()
    t.setpos(x=-30, y=-30)
    t.pencolor(pants_color)
    t.fillcolor(pants_color)
    t.pendown()
    t.begin_fill()
    for a in range(2):
        t.forward(70)
        t.left(90)
        t.forward(60)
        t.left(90)
    t.end_fill()
    # Boots
    t.penup()
    t.setpos(x=-30, y=-100)
    t.pencolor(boots_color)
    t.fillcolor(boots_color)
    t.pendown()
    t.begin_fill()
    for k in range(2):
        t.forward(20)
        t.left(90)
        t.forward(60)
        t.left(90)
    t.end_fill()
    # Shoulders
    t.penup()
    t.setpos(x=-60, y=50)
    t.pencolor(shirt_color)
    t.fillcolor(shirt_color)
    t.pendown()
    t.begin_fill()
    for h in range(4):
        t.forward(30)
        t.left(90)
    t.end_fill()
    t.penup()
    t.setpos(x=30, y=50)
    t.pendown()
    t.begin_fill()
    for g in range(4):
        t.forward(30)
        t.left(90)
    t.end_fill()
    # Arms
    t.penup()
    t.setpos(-60, y=20)
    t.pencolor(skin_color)
    t.fillcolor(skin_color)
    t.pendown()
    t.begin_fill()
    for l in range(2):
        t.forward(50)
        t.left(90)
        t.forward(30)
        t.left(90)
    t.end_fill()
    t.penup()
    t.setpos(x=30, y=20)
    t.pendown()
    t.begin_fill()
    for f in range(2):
        t.forward(50)
        t.left(90)
        t.forward(30)
        t.left(90)
    t.end_fill()
draw_steve("brown", "orange", "blue", "white", "light blue", "blue", "gray")
turtle.mainloop()